const REVISION_DATA = [
    {
        "Problem/Concept Name": "Binary Search Introduction ",
        "Topic Name": "Binary Search",
        "Link": "Binary Search: A Comprehensive Guide - LeetCode Discuss",
        "Comments": "Revise all the concepts and the problems mentioned in the page thoroughly",
        "Notes File name": "",
        "Date Added": "2025-03-02",
        "Review 1 (1 day)": "2025-03-03",
        "Review 2 (3 days)": "2025-03-05",
        "Review 3 (7 days)": "2025-03-09",
        "Review 4 (14 days)": "2025-03-16",
        "Review 5 (30 days)": "2025-04-01",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Allocate Minimum Books",
        "Topic Name": "Binary Search",
        "Link": "Allocate Minimum Pages | Practice | GeeksforGeeks",
        "Comments": "Revise based on the concepts learnt previously, binary search condition is confusing make sure to understand that also check aggressive-cows.md notes",
        "Notes File name": "aggressive-cows.md , allocate-minimum-pages.md",
        "Date Added": "2025-03-02",
        "Review 1 (1 day)": "2025-03-03",
        "Review 2 (3 days)": "2025-03-05",
        "Review 3 (7 days)": "2025-03-09",
        "Review 4 (14 days)": "2025-03-16",
        "Review 5 (30 days)": "2025-04-01",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Minimum Time to Complete Trips",
        "Topic Name": "Binary Search",
        "Link": "Minimum Time to Complete Trips - LeetCode",
        "Comments": "Revise this as you would do with Allocate min books",
        "Notes File name": "",
        "Date Added": "2025-03-02",
        "Review 1 (1 day)": "2025-03-03",
        "Review 2 (3 days)": "2025-03-05",
        "Review 3 (7 days)": "2025-03-09",
        "Review 4 (14 days)": "2025-03-16",
        "Review 5 (30 days)": "2025-04-01",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Kth smallest number in multiplication Table",
        "Topic Name": "Binary Search",
        "Link": "Kth Smallest Number in Multiplication Table - LeetCode",
        "Comments": "Extremely confusing, get the intuition clearly",
        "Notes File name": "",
        "Date Added": "2025-03-04",
        "Review 1 (1 day)": "2025-03-04",
        "Review 2 (3 days)": "2025-03-07",
        "Review 3 (7 days)": "2025-03-11",
        "Review 4 (14 days)": "2025-03-18",
        "Review 5 (30 days)": "2025-04-03",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Split Array Largest Sum",
        "Topic Name": "Binary Search",
        "Link": "Binary Search",
        "Comments": "Think well on this problem",
        "Notes File name": "",
        "Date Added": "2025-03-04",
        "Review 1 (1 day)": "2025-03-05",
        "Review 2 (3 days)": "2025-03-07",
        "Review 3 (7 days)": "2025-03-11",
        "Review 4 (14 days)": "2025-03-18",
        "Review 5 (30 days)": "2025-04-03",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Maximum-profit-in-job-scheduling",
        "Topic Name": "Binary Search, DP",
        "Link": "Maximum Profit in Job Scheduling - LeetCode",
        "Comments": "Solve this After learning DP",
        "Notes File name": "",
        "Date Added": "",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Search in a Rotated sorted Array 1 and 2",
        "Topic Name": "Binary Search",
        "Link": "Search in Rotated Sorted Array II - LeetCode",
        "Comments": "Solve both the questions, ",
        "Notes File name": "rotated-sorted-array-ii.md",
        "Date Added": "2025-03-08",
        "Review 1 (1 day)": "2025-03-09",
        "Review 2 (3 days)": "2025-03-11",
        "Review 3 (7 days)": "2025-03-15",
        "Review 4 (14 days)": "2025-03-22",
        "Review 5 (30 days)": "2025-04-07",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find Minimum in rotated sorted array",
        "Topic Name": "Binary Search",
        "Link": "Find Minimum in Rotated Sorted Array II - LeetCode",
        "Comments": "Similar to above question",
        "Notes File name": "minimum-in-rotated-sorted-array.md",
        "Date Added": "2025-03-08",
        "Review 1 (1 day)": "2025-03-09",
        "Review 2 (3 days)": "2025-03-11",
        "Review 3 (7 days)": "2025-03-15",
        "Review 4 (14 days)": "2025-03-22",
        "Review 5 (30 days)": "2025-04-07",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find Peak element",
        "Topic Name": "Binary Search",
        "Link": "Find Peak Element - LeetCode",
        "Comments": "Just give a glance on edge cases",
        "Notes File name": "find-peak-element.md",
        "Date Added": "2025-03-08",
        "Review 1 (1 day)": "2025-03-09",
        "Review 2 (3 days)": "2025-03-11",
        "Review 3 (7 days)": "2025-03-15",
        "Review 4 (14 days)": "2025-03-22",
        "Review 5 (30 days)": "2025-04-07",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Search a 2D Matrix II",
        "Topic Name": "Binary Search / Staircase travsersal",
        "Link": "Search a 2D Matrix II - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-03-08",
        "Review 1 (1 day)": "2025-03-09",
        "Review 2 (3 days)": "2025-03-11",
        "Review 3 (7 days)": "2025-03-15",
        "Review 4 (14 days)": "2025-03-22",
        "Review 5 (30 days)": "2025-04-07",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Single Element in a sorted Array",
        "Topic Name": "Binary Search",
        "Link": "https://leetcode.com/problems/single-element-in-a-sorted-array/submissions/1186309107/",
        "Comments": "",
        "Notes File name": "Just understand the code mentioned in the link",
        "Date Added": "2025-03-08",
        "Review 1 (1 day)": "2025-03-09",
        "Review 2 (3 days)": "2025-03-11",
        "Review 3 (7 days)": "2025-03-15",
        "Review 4 (14 days)": "2025-03-22",
        "Review 5 (30 days)": "2025-04-07",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find K Closest Elements",
        "Topic Name": "Two pointers, Binary Search",
        "Link": "Find K Closest Elements - LeetCode",
        "Comments": "Very tricky, understand well",
        "Notes File name": "find-k-nearest-elements.md",
        "Date Added": "2025-03-08",
        "Review 1 (1 day)": "2025-03-09",
        "Review 2 (3 days)": "2025-03-11",
        "Review 3 (7 days)": "2025-03-15",
        "Review 4 (14 days)": "2025-03-22",
        "Review 5 (30 days)": "2025-04-07",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Kth Smallest Element in a Sorted Matrix",
        "Topic Name": "Binary Search",
        "Link": "Kth Smallest Element in a Sorted Matrix - LeetCode",
        "Comments": "Can also check the video to understand well",
        "Notes File name": "https://www.youtube.com/watch?v=MOe7LlagCN8 and kth-smallest-element-in-matrix.md",
        "Date Added": "2025-03-09",
        "Review 1 (1 day)": "2025-03-10",
        "Review 2 (3 days)": "2025-03-12",
        "Review 3 (7 days)": "2025-03-16",
        "Review 4 (14 days)": "2025-03-23",
        "Review 5 (30 days)": "2025-04-08",
        "Status": ""
    },
    {
        "Problem/Concept Name": "K-th Smallest Prime Fraction",
        "Topic Name": "Binary Search",
        "Link": "K-th Smallest Prime Fraction - LeetCode",
        "Comments": "Unable to understand, see again",
        "Notes File name": "https://www.youtube.com/watch?v=SmxdebjWvfs",
        "Date Added": "",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Special Array With X Elements Greater Than or Equal X",
        "Topic Name": "BInary Search",
        "Link": "Special Array With X Elements Greater Than or Equal X - LeetCode",
        "Comments": "",
        "Notes File name": "Understand the submitted Code",
        "Date Added": "2025-03-11",
        "Review 1 (1 day)": "2025-03-12",
        "Review 2 (3 days)": "2025-03-14",
        "Review 3 (7 days)": "2025-03-18",
        "Review 4 (14 days)": "2025-03-25",
        "Review 5 (30 days)": "2025-04-10",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Minimum Number of Days to Make m Bouquets",
        "Topic Name": "Binary Search",
        "Link": "Minimum Number of Days to Make m Bouquets - LeetCode",
        "Comments": "Try to solve before seeing notes",
        "Notes File name": "minimum-number-of-days-to-make-m-bouquets.md",
        "Date Added": "2025-03-11",
        "Review 1 (1 day)": "2025-03-12",
        "Review 2 (3 days)": "2025-03-14",
        "Review 3 (7 days)": "2025-03-18",
        "Review 4 (14 days)": "2025-03-25",
        "Review 5 (30 days)": "2025-04-10",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Heaters",
        "Topic Name": "Binary Search",
        "Link": "Heaters - LeetCode",
        "Comments": "Great Question",
        "Notes File name": "",
        "Date Added": "2025-03-12",
        "Review 1 (1 day)": "2025-03-13",
        "Review 2 (3 days)": "2025-03-15",
        "Review 3 (7 days)": "2025-03-19",
        "Review 4 (14 days)": "2025-03-26",
        "Review 5 (30 days)": "2025-04-11",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Median of two Sorted Arrays",
        "Topic Name": "Binary Search",
        "Link": "Median of Two Sorted Arrays - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Russian Doll Envelopes",
        "Topic Name": "Binary Search, DP",
        "Link": "Russian Doll Envelopes - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Combination Sum II",
        "Topic Name": "Backtracking ",
        "Link": "Combination Sum II - LeetCode",
        "Comments": "Understand the code and question",
        "Notes File name": "combination-sum.md",
        "Date Added": "Understand the code and question",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "House Robber IV",
        "Topic Name": "Binary Search",
        "Link": "House Robber IV",
        "Comments": "Understand why greedy works for this problem",
        "Notes File name": "house-robber-iv.md ",
        "Date Added": "2025-03-15",
        "Review 1 (1 day)": "2025-03-16",
        "Review 2 (3 days)": "2025-03-18",
        "Review 3 (7 days)": "2025-03-22",
        "Review 4 (14 days)": "2025-03-29",
        "Review 5 (30 days)": "2025-04-14",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Longest Nice Subarray",
        "Topic Name": "Bitmasking",
        "Link": "https://leetcode.com/problems/longest-nice-subarray/description/?envType=daily-question&envId=2025-03-18",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-03-18",
        "Review 1 (1 day)": "2025-03-19",
        "Review 2 (3 days)": "2025-03-21",
        "Review 3 (7 days)": "2025-03-25",
        "Review 4 (14 days)": "2025-04-01",
        "Review 5 (30 days)": "2025-04-17",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Permutations II",
        "Topic Name": "Backtracking ",
        "Link": "Permutations II - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-03-18",
        "Review 1 (1 day)": "2025-03-19",
        "Review 2 (3 days)": "2025-03-21",
        "Review 3 (7 days)": "2025-03-25",
        "Review 4 (14 days)": "2025-04-01",
        "Review 5 (30 days)": "2025-04-17",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Combinations ",
        "Topic Name": "Backtracking ",
        "Link": "Combinations - LeetCode",
        "Comments": "",
        "Notes File name": "combinations.md",
        "Date Added": "2025-03-23",
        "Review 1 (1 day)": "2025-03-24",
        "Review 2 (3 days)": "2025-03-26",
        "Review 3 (7 days)": "2025-03-30",
        "Review 4 (14 days)": "2025-04-06",
        "Review 5 (30 days)": "2025-04-22",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Minimum Index of a Valid Split",
        "Topic Name": "Array",
        "Link": "Minimum Index of a Valid Split - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-03-24",
        "Review 1 (1 day)": "2025-03-25",
        "Review 2 (3 days)": "2025-03-27",
        "Review 3 (7 days)": "2025-03-31",
        "Review 4 (14 days)": "2025-04-07",
        "Review 5 (30 days)": "2025-04-23",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Next Greater Element",
        "Topic Name": "Stack",
        "Link": "Next Greater Element II - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-04-01",
        "Review 1 (1 day)": "2025-04-02",
        "Review 2 (3 days)": "2025-04-04",
        "Review 3 (7 days)": "2025-04-08",
        "Review 4 (14 days)": "2025-04-15",
        "Review 5 (30 days)": "2025-05-01",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Remove Duplicates from Sorted Array",
        "Topic Name": "Array",
        "Link": "Remove Duplicates from Sorted Array - LeetCode",
        "Comments": "",
        "Notes File name": "remove-duplicates-from-sorted-array.md",
        "Date Added": "2025-06-24",
        "Review 1 (1 day)": "2025-06-25",
        "Review 2 (3 days)": "2025-06-27",
        "Review 3 (7 days)": "2025-07-01",
        "Review 4 (14 days)": "2025-07-08",
        "Review 5 (30 days)": "2025-07-24",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Remove Element",
        "Topic Name": "Array",
        "Link": "Remove Element - LeetCode",
        "Comments": "",
        "Notes File name": "remove-element.md",
        "Date Added": "2025-06-24",
        "Review 1 (1 day)": "2025-06-25",
        "Review 2 (3 days)": "2025-06-27",
        "Review 3 (7 days)": "2025-07-01",
        "Review 4 (14 days)": "2025-07-08",
        "Review 5 (30 days)": "2025-07-24",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Kadane's Algo",
        "Topic Name": "Array",
        "Link": "Maximum Subarray - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-06-25",
        "Review 1 (1 day)": "2025-06-26",
        "Review 2 (3 days)": "2025-06-28",
        "Review 3 (7 days)": "2025-07-02",
        "Review 4 (14 days)": "2025-07-09",
        "Review 5 (30 days)": "2025-07-25",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Majority Element II ",
        "Topic Name": "Array",
        "Link": "Majority Element II - LeetCode",
        "Comments": "Just have a glance",
        "Notes File name": "https://www.youtube.com/watch?v=vwZj1K0e9U8",
        "Date Added": "2025-06-25",
        "Review 1 (1 day)": "2025-06-26",
        "Review 2 (3 days)": "2025-06-28",
        "Review 3 (7 days)": "2025-07-02",
        "Review 4 (14 days)": "2025-07-09",
        "Review 5 (30 days)": "2025-07-25",
        "Status": ""
    },
    {
        "Problem/Concept Name": "H-Index",
        "Topic Name": "Array",
        "Link": "H-Index - LeetCode",
        "Comments": "Also check H-Index II - tricky",
        "Notes File name": "h-index.md",
        "Date Added": "2025-06-26",
        "Review 1 (1 day)": "2025-06-27",
        "Review 2 (3 days)": "2025-06-29",
        "Review 3 (7 days)": "2025-07-03",
        "Review 4 (14 days)": "2025-07-10",
        "Review 5 (30 days)": "2025-07-26",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Maximum Sum Circular Subarray",
        "Topic Name": "Array",
        "Link": "Maximum Sum Circular Subarray - LeetCode",
        "Comments": "Compare it with Kadane",
        "Notes File name": "maximum-subarray-sum-circular.md",
        "Date Added": "2025-06-28",
        "Review 1 (1 day)": "2025-06-29",
        "Review 2 (3 days)": "2025-07-01",
        "Review 3 (7 days)": "2025-07-05",
        "Review 4 (14 days)": "2025-07-12",
        "Review 5 (30 days)": "2025-07-28",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Merge Sort",
        "Topic Name": "Array",
        "Link": "Merge Sort | Practice | GeeksforGeeks",
        "Comments": "",
        "Notes File name": "https://www.youtube.com/watch?v=ogjf7ORKfd8&t=143s",
        "Date Added": "2025-06-29",
        "Review 1 (1 day)": "2025-06-30",
        "Review 2 (3 days)": "2025-07-02",
        "Review 3 (7 days)": "2025-07-06",
        "Review 4 (14 days)": "2025-07-13",
        "Review 5 (30 days)": "2025-07-29",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Global and Local Inversions",
        "Topic Name": "Array",
        "Link": "Global and Local Inversions - LeetCode",
        "Comments": "Understand both the solutions for the problem in the link",
        "Notes File name": "https://leetcode.com/problems/global-and-local-inversions/solutions/113644/c-java-python-easy-and-concise-solution/",
        "Date Added": "2025-06-29",
        "Review 1 (1 day)": "2025-06-30",
        "Review 2 (3 days)": "2025-07-02",
        "Review 3 (7 days)": "2025-07-06",
        "Review 4 (14 days)": "2025-07-13",
        "Review 5 (30 days)": "2025-07-29",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Rabin Karp",
        "Topic Name": "String",
        "Link": "https://takeuforward.org/plus/dsa/strings--advanced-algo/advanced-problems-(less-asked)/rabin-karp-algorithm",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-07-08",
        "Review 1 (1 day)": "2025-07-09",
        "Review 2 (3 days)": "2025-07-11",
        "Review 3 (7 days)": "2025-07-15",
        "Review 4 (14 days)": "2025-07-22",
        "Review 5 (30 days)": "2025-08-07",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Greedy Notes",
        "Topic Name": "Greedy",
        "Link": "Mastering the Greedy Algorithm: From LeetCode Puzzles to Infrastructure | by Lagu | May, 2025 | Medium",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Jump Game I and II",
        "Topic Name": "Greedy",
        "Link": "Jump Game II - LeetCode",
        "Comments": "",
        "Notes File name": "L5. Jump Game - II | Greedy Algorithm Playlist",
        "Date Added": "2025-07-24",
        "Review 1 (1 day)": "2025-07-25",
        "Review 2 (3 days)": "2025-07-27",
        "Review 3 (7 days)": "2025-07-31",
        "Review 4 (14 days)": "2025-08-07",
        "Review 5 (30 days)": "2025-08-23",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Non-overlapping intervals",
        "Topic Name": "Greedy",
        "Link": "Non-overlapping Intervals - LeetCode",
        "Comments": "",
        "Notes File name": "non-overlapping-intervals.md",
        "Date Added": "2025-07-25",
        "Review 1 (1 day)": "2025-07-26",
        "Review 2 (3 days)": "2025-07-28",
        "Review 3 (7 days)": "2025-08-01",
        "Review 4 (14 days)": "2025-08-08",
        "Review 5 (30 days)": "2025-08-24",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Gas Station",
        "Topic Name": "Greedy",
        "Link": "Gas Station - LeetCode",
        "Comments": "Tricky, Understand well",
        "Notes File name": "",
        "Date Added": "2025-07-25",
        "Review 1 (1 day)": "2025-07-26",
        "Review 2 (3 days)": "2025-07-28",
        "Review 3 (7 days)": "2025-08-01",
        "Review 4 (14 days)": "2025-08-08",
        "Review 5 (30 days)": "2025-08-24",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Car Pooling",
        "Topic Name": "Greedy",
        "Link": "Car Pooling",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-07-25",
        "Review 1 (1 day)": "2025-07-26",
        "Review 2 (3 days)": "2025-07-28",
        "Review 3 (7 days)": "2025-08-01",
        "Review 4 (14 days)": "2025-08-08",
        "Review 5 (30 days)": "2025-08-24",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Car Fleet",
        "Topic Name": "Greedy",
        "Link": "Car Fleet - LeetCode",
        "Comments": "",
        "Notes File name": "https://www.youtube.com/watch?v=Pr6T-3yB9RM",
        "Date Added": "2025-07-26",
        "Review 1 (1 day)": "2025-07-27",
        "Review 2 (3 days)": "2025-07-29",
        "Review 3 (7 days)": "2025-08-02",
        "Review 4 (14 days)": "2025-08-09",
        "Review 5 (30 days)": "2025-08-25",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find Valid Matrix Given Row and Column Sums",
        "Topic Name": "Greedy",
        "Link": "1605. Find Valid Matrix Given Row and Column Sums",
        "Comments": "",
        "Notes File name": "Find Valid Matrix Given Row and Column Sums.md",
        "Date Added": "2025-07-26",
        "Review 1 (1 day)": "2025-07-27",
        "Review 2 (3 days)": "2025-07-29",
        "Review 3 (7 days)": "2025-08-02",
        "Review 4 (14 days)": "2025-08-09",
        "Review 5 (30 days)": "2025-08-25",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find the Maximum Length of Valid Subsequence I",
        "Topic Name": "Greedy",
        "Link": "Find the Maximum Length of Valid Subsequence I - LeetCode",
        "Comments": "",
        "Notes File name": "Find the Maximum Length of Valid Subsequence I.md",
        "Date Added": "2025-07-26",
        "Review 1 (1 day)": "2025-07-27",
        "Review 2 (3 days)": "2025-07-29",
        "Review 3 (7 days)": "2025-08-02",
        "Review 4 (14 days)": "2025-08-09",
        "Review 5 (30 days)": "2025-08-25",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Prefix Sum Complete Guide (Have a glance on all the problems)",
        "Topic Name": "Prefix Sum",
        "Link": "Discuss - LeetCode",
        "Comments": "",
        "Notes File name": "Read the notes first and go to the problems below",
        "Date Added": "2025-07-28",
        "Review 1 (1 day)": "2025-07-29",
        "Review 2 (3 days)": "2025-07-31",
        "Review 3 (7 days)": "2025-08-04",
        "Review 4 (14 days)": "2025-08-11",
        "Review 5 (30 days)": "2025-08-27",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Subarray Sum Equals K",
        "Topic Name": "Prefix Sum",
        "Link": "Subarray Sum Equals K - LeetCode",
        "Comments": "",
        "Notes File name": "subarray-sum-equals-k.md",
        "Date Added": "2025-07-28",
        "Review 1 (1 day)": "2025-07-29",
        "Review 2 (3 days)": "2025-07-31",
        "Review 3 (7 days)": "2025-08-04",
        "Review 4 (14 days)": "2025-08-11",
        "Review 5 (30 days)": "2025-08-27",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Count Number of Bad Pairs",
        "Topic Name": "Prefix Sum",
        "Link": "Count Number of Bad Pairs - LeetCode",
        "Comments": "",
        "Notes File name": "count-bad-pairs.md",
        "Date Added": "2025-07-28",
        "Review 1 (1 day)": "2025-07-29",
        "Review 2 (3 days)": "2025-07-31",
        "Review 3 (7 days)": "2025-08-04",
        "Review 4 (14 days)": "2025-08-11",
        "Review 5 (30 days)": "2025-08-27",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Minimum Operations to Reduce X to Zero",
        "Topic Name": "Prefix Sum",
        "Link": "Minimum Operations to Reduce X to Zero - LeetCode",
        "Comments": "",
        "Notes File name": "minimum-operations-to-x.md",
        "Date Added": "2025-07-28",
        "Review 1 (1 day)": "2025-07-29",
        "Review 2 (3 days)": "2025-07-31",
        "Review 3 (7 days)": "2025-08-04",
        "Review 4 (14 days)": "2025-08-11",
        "Review 5 (30 days)": "2025-08-27",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Subbarray Sum Divisible by K",
        "Topic Name": "Prefix Sum",
        "Link": "Subarray Sums Divisible by K - LeetCode",
        "Comments": "",
        "Notes File name": "divisibilty-rule.md",
        "Date Added": "2025-07-28",
        "Review 1 (1 day)": "2025-07-29",
        "Review 2 (3 days)": "2025-07-31",
        "Review 3 (7 days)": "2025-08-04",
        "Review 4 (14 days)": "2025-08-11",
        "Review 5 (30 days)": "2025-08-27",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Check If Array Pairs Are Divisible by k",
        "Topic Name": "Prefix Sum",
        "Link": "Check If Array Pairs Are Divisible by k - LeetCode",
        "Comments": "",
        "Notes File name": "check-if-array-pairs-are-divisible-by-k.md",
        "Date Added": "2025-07-29",
        "Review 1 (1 day)": "2025-07-30",
        "Review 2 (3 days)": "2025-08-01",
        "Review 3 (7 days)": "2025-08-05",
        "Review 4 (14 days)": "2025-08-12",
        "Review 5 (30 days)": "2025-08-28",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Count of Interesting Subarrays",
        "Topic Name": "Prefix Sum",
        "Link": "Count of Interesting Subarrays - LeetCode",
        "Comments": "",
        "Notes File name": "count-of-interesting-subarrays.md",
        "Date Added": "2025-07-29",
        "Review 1 (1 day)": "2025-07-30",
        "Review 2 (3 days)": "2025-08-01",
        "Review 3 (7 days)": "2025-08-05",
        "Review 4 (14 days)": "2025-08-12",
        "Review 5 (30 days)": "2025-08-28",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Range Sum Query 2D - Immutable",
        "Topic Name": "Prefix Sum",
        "Link": "Range Sum Query 2D - Immutable - LeetCode",
        "Comments": "",
        "Notes File name": "range-sum-query-2d-immutable.md",
        "Date Added": "2025-07-30",
        "Review 1 (1 day)": "2025-07-31",
        "Review 2 (3 days)": "2025-08-02",
        "Review 3 (7 days)": "2025-08-06",
        "Review 4 (14 days)": "2025-08-13",
        "Review 5 (30 days)": "2025-08-29",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Matrix Block Sum",
        "Topic Name": "Prefix Sum",
        "Link": "https://leetcode.com/problems/matrix-block-sum/description/",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-07-30",
        "Review 1 (1 day)": "2025-07-31",
        "Review 2 (3 days)": "2025-08-02",
        "Review 3 (7 days)": "2025-08-06",
        "Review 4 (14 days)": "2025-08-13",
        "Review 5 (30 days)": "2025-08-29",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Product of Array Except Self",
        "Topic Name": "Prefix Sum",
        "Link": "Product of Array Except Self - LeetCode",
        "Comments": "",
        "Notes File name": "For the optimized o(1) space approach, Understand the last submitted code",
        "Date Added": "2025-07-31",
        "Review 1 (1 day)": "2025-08-01",
        "Review 2 (3 days)": "2025-08-03",
        "Review 3 (7 days)": "2025-08-07",
        "Review 4 (14 days)": "2025-08-14",
        "Review 5 (30 days)": "2025-08-30",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Minimum Operations to Make Binary Array Elements Equal to One II",
        "Topic Name": "Prefix Sum",
        "Link": "Minimum Operations to Make Binary Array Elements Equal to One II - LeetCode",
        "Comments": "",
        "Notes File name": "Understand the submitted code with comments, Kinda tricky",
        "Date Added": "2025-07-31",
        "Review 1 (1 day)": "2025-08-01",
        "Review 2 (3 days)": "2025-08-03",
        "Review 3 (7 days)": "2025-08-07",
        "Review 4 (14 days)": "2025-08-14",
        "Review 5 (30 days)": "2025-08-30",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Longest Consecutive Sequence",
        "Topic Name": "Hashmap",
        "Link": "Longest Consecutive Sequence - LeetCode",
        "Comments": "Just have a glance to the solution",
        "Notes File name": "",
        "Date Added": "2025-07-31",
        "Review 1 (1 day)": "2025-08-01",
        "Review 2 (3 days)": "2025-08-03",
        "Review 3 (7 days)": "2025-08-07",
        "Review 4 (14 days)": "2025-08-14",
        "Review 5 (30 days)": "2025-08-30",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Insert Delete GetRandom O(1)",
        "Topic Name": "Hashmap",
        "Link": "Insert Delete GetRandom O(1) - LeetCode",
        "Comments": "Just have a glance to the solution",
        "Notes File name": "",
        "Date Added": "2025-07-31",
        "Review 1 (1 day)": "2025-08-01",
        "Review 2 (3 days)": "2025-08-03",
        "Review 3 (7 days)": "2025-08-07",
        "Review 4 (14 days)": "2025-08-14",
        "Review 5 (30 days)": "2025-08-30",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Employee Importance",
        "Topic Name": "Hashmap",
        "Link": "Employee Importance - LeetCode",
        "Comments": "Just have a glance to the solution",
        "Notes File name": "",
        "Date Added": "2025-08-01",
        "Review 1 (1 day)": "2025-08-02",
        "Review 2 (3 days)": "2025-08-04",
        "Review 3 (7 days)": "2025-08-08",
        "Review 4 (14 days)": "2025-08-15",
        "Review 5 (30 days)": "2025-08-31",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Number of Boomerangs",
        "Topic Name": "Hashmap",
        "Link": "Number of Boomerangs - LeetCode",
        "Comments": "",
        "Notes File name": "number-of-boomerangs.md",
        "Date Added": "2025-08-01",
        "Review 1 (1 day)": "2025-08-02",
        "Review 2 (3 days)": "2025-08-04",
        "Review 3 (7 days)": "2025-08-08",
        "Review 4 (14 days)": "2025-08-15",
        "Review 5 (30 days)": "2025-08-31",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find All Duplicates in an Array",
        "Topic Name": "Hashmap",
        "Link": "Find All Duplicates in an Array - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-08-01",
        "Review 1 (1 day)": "2025-08-02",
        "Review 2 (3 days)": "2025-08-04",
        "Review 3 (7 days)": "2025-08-08",
        "Review 4 (14 days)": "2025-08-15",
        "Review 5 (30 days)": "2025-08-31",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Linked List",
        "Topic Name": "Linked List",
        "Link": "Look into the questions of LinkedList in file:///Users/koushikcherukuri/Downloads/DSA%20Topic%20Wise%20Questions.pdf",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-08-01",
        "Review 1 (1 day)": "2025-08-02",
        "Review 2 (3 days)": "2025-08-04",
        "Review 3 (7 days)": "2025-08-08",
        "Review 4 (14 days)": "2025-08-15",
        "Review 5 (30 days)": "2025-08-31",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Palindrome Linked List",
        "Topic Name": "Linked List",
        "Link": "Palindrome Linked List - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-08-02",
        "Review 1 (1 day)": "2025-08-03",
        "Review 2 (3 days)": "2025-08-05",
        "Review 3 (7 days)": "2025-08-09",
        "Review 4 (14 days)": "2025-08-16",
        "Review 5 (30 days)": "2025-09-01",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Remove Nth Node From End of List",
        "Topic Name": "Linked List",
        "Link": "Remove Nth Node From End of List - LeetCode",
        "Comments": "",
        "Notes File name": "remove-nth-node-from-end-of-list.md",
        "Date Added": "2025-08-02",
        "Review 1 (1 day)": "2025-08-03",
        "Review 2 (3 days)": "2025-08-05",
        "Review 3 (7 days)": "2025-08-09",
        "Review 4 (14 days)": "2025-08-16",
        "Review 5 (30 days)": "2025-09-01",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Partition List",
        "Topic Name": "Linked List",
        "Link": "Partition List - LeetCode",
        "Comments": "",
        "Notes File name": "partition-list.md",
        "Date Added": "2025-08-03",
        "Review 1 (1 day)": "2025-08-04",
        "Review 2 (3 days)": "2025-08-06",
        "Review 3 (7 days)": "2025-08-10",
        "Review 4 (14 days)": "2025-08-17",
        "Review 5 (30 days)": "2025-09-02",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Copy List with Random Pointer",
        "Topic Name": "Linked List",
        "Link": "Copy List with Random Pointer - LeetCode",
        "Comments": "",
        "Notes File name": "copy-list-with-random-pointer.md",
        "Date Added": "2025-08-03",
        "Review 1 (1 day)": "2025-08-04",
        "Review 2 (3 days)": "2025-08-06",
        "Review 3 (7 days)": "2025-08-10",
        "Review 4 (14 days)": "2025-08-17",
        "Review 5 (30 days)": "2025-09-02",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find the Minimum and Maximum Number of Nodes Between Critical Points",
        "Topic Name": "Linked List",
        "Link": "https://leetcode.com/problems/find-the-minimum-and-maximum-number-of-nodes-between-critical-points/description/",
        "Comments": "",
        "Notes File name": "Just see the problem",
        "Date Added": "2025-08-05",
        "Review 1 (1 day)": "2025-08-06",
        "Review 2 (3 days)": "2025-08-08",
        "Review 3 (7 days)": "2025-08-12",
        "Review 4 (14 days)": "2025-08-19",
        "Review 5 (30 days)": "2025-09-04",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Double a Number Represented as a Linked List",
        "Topic Name": "Linked List",
        "Link": "https://leetcode.com/problems/double-a-number-represented-as-a-linked-list/description/",
        "Comments": "",
        "Notes File name": "Just see the problem",
        "Date Added": "2025-08-05",
        "Review 1 (1 day)": "2025-08-06",
        "Review 2 (3 days)": "2025-08-08",
        "Review 3 (7 days)": "2025-08-12",
        "Review 4 (14 days)": "2025-08-19",
        "Review 5 (30 days)": "2025-09-04",
        "Status": ""
    },
    {
        "Problem/Concept Name": "LRU Cache",
        "Topic Name": "linked List",
        "Link": "LRU Cache - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-08-05",
        "Review 1 (1 day)": "2025-08-06",
        "Review 2 (3 days)": "2025-08-08",
        "Review 3 (7 days)": "2025-08-12",
        "Review 4 (14 days)": "2025-08-19",
        "Review 5 (30 days)": "2025-09-04",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Merge k Sorted Lists",
        "Topic Name": "Linked List",
        "Link": "Merge k Sorted Lists - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-08-06",
        "Review 1 (1 day)": "2025-08-07",
        "Review 2 (3 days)": "2025-08-09",
        "Review 3 (7 days)": "2025-08-13",
        "Review 4 (14 days)": "2025-08-20",
        "Review 5 (30 days)": "2025-09-05",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Count Complete Tree Nodes",
        "Topic Name": "Binary Tree",
        "Link": "Count Complete Tree Nodes - LeetCode",
        "Comments": "",
        "Notes File name": "https://www.youtube.com/watch?v=u-yWemKGWO0",
        "Date Added": "2025-08-07",
        "Review 1 (1 day)": "2025-08-08",
        "Review 2 (3 days)": "2025-08-10",
        "Review 3 (7 days)": "2025-08-14",
        "Review 4 (14 days)": "2025-08-21",
        "Review 5 (30 days)": "2025-09-06",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Binary Tree Right Side View",
        "Topic Name": "Binary Tree",
        "Link": "Binary Tree Right Side View - LeetCode",
        "Comments": "Understand the recursive solution",
        "Notes File name": "",
        "Date Added": "2025-08-13",
        "Review 1 (1 day)": "2025-08-14",
        "Review 2 (3 days)": "2025-08-16",
        "Review 3 (7 days)": "2025-08-20",
        "Review 4 (14 days)": "2025-08-27",
        "Review 5 (30 days)": "2025-09-12",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Lowest Common Ancestor",
        "Topic Name": "Binary Tree",
        "Link": "Lowest Common Ancestor of a Binary Tree - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-08-14",
        "Review 1 (1 day)": "2025-08-15",
        "Review 2 (3 days)": "2025-08-17",
        "Review 3 (7 days)": "2025-08-21",
        "Review 4 (14 days)": "2025-08-28",
        "Review 5 (30 days)": "2025-09-13",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Path Sum III",
        "Topic Name": "Binary Tree",
        "Link": "Path Sum III - LeetCode",
        "Comments": "Have a glance",
        "Notes File name": "",
        "Date Added": "2025-08-14",
        "Review 1 (1 day)": "2025-08-15",
        "Review 2 (3 days)": "2025-08-17",
        "Review 3 (7 days)": "2025-08-21",
        "Review 4 (14 days)": "2025-08-28",
        "Review 5 (30 days)": "2025-09-13",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Maximum Width of Binary Tree",
        "Topic Name": "Binary Tree",
        "Link": "Maximum Width of Binary Tree - LeetCode",
        "Comments": "Also check the question -> https://leetcode.com/problems/check-completeness-of-a-binary-tree/description/",
        "Notes File name": "maximum-width-of-binary-tree.md",
        "Date Added": "2025-08-14",
        "Review 1 (1 day)": "2025-08-15",
        "Review 2 (3 days)": "2025-08-17",
        "Review 3 (7 days)": "2025-08-21",
        "Review 4 (14 days)": "2025-08-28",
        "Review 5 (30 days)": "2025-09-13",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Construct Binary Tree from Preorder and Inorder Traversal",
        "Topic Name": "Binary Tree",
        "Link": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description/",
        "Comments": "Also solve the inorder-postorder problem",
        "Notes File name": "construct-binary-tree-from-preorder-and-inorder-traversal.md",
        "Date Added": "2025-08-16",
        "Review 1 (1 day)": "2025-08-17",
        "Review 2 (3 days)": "2025-08-19",
        "Review 3 (7 days)": "2025-08-23",
        "Review 4 (14 days)": "2025-08-30",
        "Review 5 (30 days)": "2025-09-15",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Morris Traversal",
        "Topic Name": "Binary tree",
        "Link": "",
        "Comments": "Do dry run to understand",
        "Notes File name": "morris-traversal.md",
        "Date Added": "2025-08-16",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Populating Next Right Pointers in Each Node",
        "Topic Name": "Binary Tree",
        "Link": "Populating Next Right Pointers in Each Node - LeetCode",
        "Comments": "Solve this question with the below problem's solution",
        "Notes File name": "populating-next-right-pointers-in-each-node.md",
        "Date Added": "2025-08-16",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Populating Next Right Pointers in Each Node ii",
        "Topic Name": "Binary Tree",
        "Link": "Populating Next Right Pointers in Each Node II - LeetCode",
        "Comments": "Populating Next Right Pointers in Each Node II | Live Coding with Explanation | Leetcode - 117 - YouTube",
        "Notes File name": "populating-next-right-pointers-in-each-node-ii.md",
        "Date Added": "2025-08-16",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "All Nodes Distance K in Binary Tree",
        "Topic Name": "Binary Tree",
        "Link": "All Nodes Distance K in Binary Tree - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2025-08-17",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Distribute coins in a Binary Tree",
        "Topic Name": "Binary Tree",
        "Link": "Distribute Coins in Binary Tree - LeetCode",
        "Comments": "",
        "Notes File name": "distribute-coins-in-binary-tree.md",
        "Date Added": "2025-08-17",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Delete Nodes And Return Forest",
        "Topic Name": "Binary Tree",
        "Link": "Delete Nodes And Return Forest - LeetCode",
        "Comments": "In this question understand why postorder is used and also understand the importance of postorder",
        "Notes File name": "delete-nodes-and-return-forest.md",
        "Date Added": "2025-08-17",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Delete Leaves With a Given Value",
        "Topic Name": "Binary Tree",
        "Link": "https://leetcode.com/problems/delete-leaves-with-a-given-value/description/",
        "Comments": "",
        "Notes File name": "Have a glance",
        "Date Added": "2025-08-17",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Create Binary Tree From Descriptions",
        "Topic Name": "Binary Tree",
        "Link": "Create Binary Tree From Descriptions - LeetCode",
        "Comments": "",
        "Notes File name": "Understand the solution",
        "Date Added": "2025-08-17",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Number of Good Leaf Nodes Pairs",
        "Topic Name": "Binary Tree",
        "Link": "Number of Good Leaf Nodes Pairs - LeetCode",
        "Comments": "",
        "Notes File name": "Understand the solution",
        "Date Added": "2025-08-18",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Step-By-Step Directions From a Binary Tree Node to Another",
        "Topic Name": "Binary Tree",
        "Link": "Step-By-Step Directions From a Binary Tree Node to Another - LeetCode",
        "Comments": "",
        "Notes File name": "https://leetcode.com/problems/step-by-step-directions-from-a-binary-tree-node-to-another/solutions/1613071/idea-explained-lca-tree-traversal-backtracking-c-clean-code/",
        "Date Added": "2025-08-18",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Find Duplicate Subtrees",
        "Topic Name": "Binary Tree",
        "Link": "Find Duplicate Subtrees - LeetCode",
        "Comments": "",
        "Notes File name": "Find Duplicate Subtrees - Leetcode 652 - Python - YouTube",
        "Date Added": "2025-08-19",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Vertical Order Traversal of a Binary Tree",
        "Topic Name": "Binary Tree",
        "Link": "Vertical Order Traversal of a Binary Tree - LeetCode",
        "Comments": "",
        "Notes File name": "Just have a glance to the solution",
        "Date Added": "2025-08-19",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Maximum Sum BST in Binary Tree",
        "Topic Name": "Binary Tree",
        "Link": "Maximum Sum BST in Binary Tree - LeetCode",
        "Comments": "",
        "Notes File name": "maximum-sum-bst-in-binary-tree.md",
        "Date Added": "2025-08-19",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Convert Sorted Array to Binary Search Tree",
        "Topic Name": "BST",
        "Link": "Convert Sorted Array to Binary Search Tree - LeetCode",
        "Comments": "",
        "Notes File name": "Just have a glance to the solution",
        "Date Added": "2025-08-19",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Validate Binary Search Tree",
        "Topic Name": "BST",
        "Link": "Validate Binary Search Tree - LeetCode",
        "Comments": "",
        "Notes File name": "Just have a glance to the solution",
        "Date Added": "2025-08-19",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "BST Iterator",
        "Topic Name": "BST",
        "Link": "Binary Search Tree Iterator - LeetCode",
        "Comments": "",
        "Notes File name": "L50. Binary Search Tree Iterator | BST | O(H) Space - YouTube",
        "Date Added": "2025-08-21",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Recover BST",
        "Topic Name": "BST",
        "Link": "Recover Binary Search Tree - LeetCode",
        "Comments": "",
        "Notes File name": "L52. Recover BST | Correct BST with two nodes swapped",
        "Date Added": "2025-08-23",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Balance a Binary Search Tree",
        "Topic Name": "BST",
        "Link": "Balance a Binary Search Tree - LeetCode",
        "Comments": "",
        "Notes File name": "Just have a glance to the solution",
        "Date Added": "2025-08-23",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Delete Node in a BST",
        "Topic Name": "BST",
        "Link": "Delete Node in a BST - LeetCode",
        "Comments": "",
        "Notes File name": "https://leetcode.com/problems/delete-node-in-a-bst/solutions/1590789/c-shortest-recursive-solution-detailed-explanation-with-images/",
        "Date Added": "2025-08-23",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Min Cost climbing stairs",
        "Topic Name": "DP",
        "Link": "Min Cost Climbing Stairs - LeetCode",
        "Comments": "",
        "Notes File name": "min-cost-climbing-stairs.md",
        "Date Added": "2025-08-26",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "0 1 Knapsack (DP on subsequences)",
        "Topic Name": "DP",
        "Link": "0 - 1 Knapsack Problem | Practice | GeeksforGeeks",
        "Comments": "Look into all of the problems in this pattern from Aditya verma",
        "Notes File name": "See Aditya verma's video",
        "Date Added": "2025-08-29",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "DP on Grids",
        "Topic Name": "DP",
        "Link": "https://takeuforward.org/plus/dsa/dynamic-programming/dp-on-grids/grid-unique-paths?tab=editorial",
        "Comments": "Solve all the questions for this pattern from TUF",
        "Notes File name": "Make sure to check all the questions from TUF for DP",
        "Date Added": "2025-08-31",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Cherry Pickup II",
        "Topic Name": "DP,",
        "Link": "Cherry Pickup II - LeetCode",
        "Comments": "Understand all the solutions, Kinda hard",
        "Notes File name": "https://takeuforward.org/plus/dsa/dynamic-programming/dp-on-grids/cherry-pickup-ii?tab=editorial",
        "Date Added": "2025-08-31",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Stock Based Questions",
        "Topic Name": "DP",
        "Link": "https://takeuforward.org/plus/dsa/dynamic-programming/dp-on-stocks/best-time-to-buy-and-sell-stock",
        "Comments": "Check all the questions",
        "Notes File name": "",
        "Date Added": "2025-09-03",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Best Time to Buy and Sell Stock II",
        "Topic Name": "DP",
        "Link": "Best Time to Buy and Sell Stock II - LeetCode",
        "Comments": "Check the tabulation approach from Striver",
        "Notes File name": "https://takeuforward.org/plus/dsa/dynamic-programming/dp-on-stocks/best-time-to-buy-and-sell-stock-ii?tab=editorial",
        "Date Added": "2025-09-03",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "LIS",
        "Topic Name": "Binary Search",
        "Link": "DP 43. Longest Increasing Subsequence | Binary Search | Intuition",
        "Comments": "Learn the Binary search approach",
        "Notes File name": "",
        "Date Added": "2025-09-08",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Largest Divisible Subset",
        "Topic Name": "DP",
        "Link": "Largest Divisible Subset | LIS Variant | DP Concepts & Qns-18 | Leetcode-368",
        "Comments": "Learn the intuitive Tabulation approach for LIS",
        "Notes File name": "",
        "Date Added": "2025-09-09",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Maths Questions",
        "Topic Name": "Math",
        "Link": "",
        "Comments": "Saw the easy questions - Solve the medium and hard questions later",
        "Notes File name": "",
        "Date Added": "2025-09-23",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Rotate Image",
        "Topic Name": "Matrix",
        "Link": "Rotate Image - LeetCode",
        "Comments": "Just see the way to Rotate image clockwise and anti clockwise",
        "Notes File name": "https://leetcode.com/problems/rotate-image/solutions/18872/a-common-method-to-rotate-the-image/",
        "Date Added": "2025-09-23",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Surrounded Regions",
        "Topic Name": "Matrix",
        "Link": "Surrounded Regions - LeetCode",
        "Comments": "Understand and solve",
        "Notes File name": "",
        "Date Added": "2025-09-24",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Implement Min stack",
        "Topic Name": "Stack",
        "Link": "Min Stack - LeetCode",
        "Comments": "See the solution, very good one",
        "Notes File name": "https://leetcode.com/problems/min-stack/submissions/1792323313/",
        "Date Added": "2025-10-05",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Simplify Path",
        "Topic Name": "Stack",
        "Link": "Simplify Path - LeetCode",
        "Comments": "",
        "Notes File name": "https://leetcode.com/problems/simplify-path/submissions/1792355872/",
        "Date Added": "2025-10-05",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Swim in Rising Water",
        "Topic Name": "Graph, Binary search",
        "Link": "Swim in Rising Water - LeetCode",
        "Comments": "Understand both the solutions",
        "Notes File name": "",
        "Date Added": "2025-10-06",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Remove K digits",
        "Topic Name": "Stack",
        "Link": "Remove K Digits - LeetCode",
        "Comments": "Understand why monotonic works",
        "Notes File name": "remove-k-elements.md",
        "Date Added": "2025-10-06",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Stock Span",
        "Topic Name": "Stack",
        "Link": "Online Stock Span - LeetCode",
        "Comments": "Apply the monotonic idea in the below guide",
        "Notes File name": "",
        "Date Added": "2025-10-06",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Monotonic stack Guide (Solve all the problems)",
        "Topic Name": "Stack",
        "Link": "https://leetcode.com/discuss/post/2347639/a-comprehensive-guide-and-template-for-m-irii/",
        "Comments": "Study how to solve monotonic stack problems",
        "Notes File name": "A comprehensive guide and template for monotonic stack based problems - Discuss - LeetCode",
        "Date Added": "2025-10-07",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "132 Pattern",
        "Topic Name": "Stack",
        "Link": "132 Pattern - LeetCode",
        "Comments": "",
        "Notes File name": "A comprehensive guide and template for monotonic stack based problems - Discuss - LeetCode",
        "Date Added": "2025-10-08",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Sliding Window Concept",
        "Topic Name": "Sliding Window",
        "Link": "Sliding Window Technique: A Comprehensive Guide - Discuss - LeetCode",
        "Comments": "",
        "Notes File name": "https://leetcode.com/discuss/post/3722472/sliding-window-technique-a-comprehensive-ix2k/",
        "Date Added": "2025-11-03",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Maximum Sum of Distinct Subarrays With Length K",
        "Topic Name": "Sliding Window",
        "Link": "Maximum Sum of Distinct Subarrays With Length K - LeetCode",
        "Comments": "Solve this using the previous guide",
        "Notes File name": "",
        "Date Added": "2025-11-03",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Longest path in a DAG",
        "Topic Name": "Graph",
        "Link": "https://leetcode.com/discuss/post/7586410/google-swe3-phonescreen-question-ctc-60l-lrcb/",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2026-02-17",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Evaluate Division",
        "Topic Name": "Graph ",
        "Link": "https://leetcode.com/problems/evaluate-division/description/?envType=problem-list-v2&envId=shortest-path",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2026-02-18",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    },
    {
        "Problem/Concept Name": "Append K Integers With Minimal Sum",
        "Topic Name": "Simulation",
        "Link": "Append K Integers With Minimal Sum - LeetCode",
        "Comments": "",
        "Notes File name": "",
        "Date Added": "2026-03-03",
        "Review 1 (1 day)": "",
        "Review 2 (3 days)": "",
        "Review 3 (7 days)": "",
        "Review 4 (14 days)": "",
        "Review 5 (30 days)": "",
        "Status": ""
    }
];
